# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'social' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'CYLTabBarController', '~> 1.29.0'
pod 'AFNNetworking', '~> 3.4.8'
pod 'SDWebImage', '~> 5.8.4'
pod 'MJExtension', '~> 3.2.2'
pod 'Masonry', '~> 1.1.0'
pod 'JXCategoryView', '~> 1.5.6'
pod 'MJRefresh', '~> 3.5.0'
pod 'TZImagePickerController', '~> 3.4.2'
pod 'YYText', '~> 1.0.7'
pod 'IQKeyboardManager', '~> 6.5.6'
pod 'EasyShowView', '~> 2.1.4'
pod 'JKCountDownButton', '~> 1.3.0'
 pod 'RongCloudIM', '~> 4.0.2'
 pod 'PGDatePicker'
pod 'SGQRCode', '~> 3.0.1'

pod 'EBPhotoPages', '~> 0.9.2'   # 图片浏览器
pod 'ELCImagePickerController', '~> 0.2.0' #图片选择器

  # Pods for social

end
